import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiOpenjdk,
  SiPython,
  SiGo,
  SiRust,
  SiPostgresql,
  SiSqlite,
  SiReact,
  SiNodedotjs,
  SiExpress,
  SiSocketdotio,
  SiFastapi,
  SiGit,
  SiPrometheus,
  SiDocker,
  SiKubernetes,
  SiAmazonwebservices,
  SiJsonwebtokens,
  SiSharp,
  SiCplusplus,
  SiUnity,
  SiUnrealengine,
  SiGooglecloud,
  SiSwift,
  SiRedis,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  java: SiOpenjdk,
  python: SiPython,
  go: SiGo,
  rust: SiRust,
  postgresql: SiPostgresql,
  sqlite: SiSqlite,
  react: SiReact,
  nodejs: SiNodedotjs,
  express: SiExpress,
  socketio: SiSocketdotio,
  fastapi: SiFastapi,
  git: SiGit,
  prometheus: SiPrometheus,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  aws: SiAmazonwebservices,
  jwt: SiJsonwebtokens,
  csharp: SiSharp,
  cpp: SiCplusplus,
  unity: SiUnity,
  unrealengine: SiUnrealengine,
  googlecloud: SiGooglecloud,
  swift: SiSwift,
  redis: SiRedis,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
